' Gambas module file

Public Sub limpiaFilaActual(grid As Gridview, f As Integer)

    Dim a As Integer

    For a = 0 To grid.columns.count - 1
        grid[f, a].text = ""
    Next

End

Public Function normalizacion(NombreEquipo As String) As String

    Dim PalabrasQuitar As New String[]
    Dim tokens As String

    'trozos de palabras a quitar para normalizar nombre
    PalabrasQuitar = ["REAL ", "DEPORTIVO ", "R.", "R. ", "D.", "D. ", "DEPORTIVO", "RC ", "CF", "RDC ", "RDC", "MANCHESTER ", "MAN ", "UP ", "SD ", "SCD ", "CD ", "UE ", "ATLETICO ", "ATLETICO", "ATLÉTICO ", "ATLÉTICO", "ATLéTICO ", "ATLéTICO", "UD ", "FC "]

    NombreEquipo = Upper(NombreEquipo)

    For Each tokens In PalabrasQuitar
        NombreEquipo = Replace(NombreEquipo, tokens, "")
    Next

    NombreEquipo = Replace(NombreEquipo, "UTD", "UNITED")

    NombreEquipo &= "    " 'añado algunos espacios para que no de problemas el mid

    Return Mid$(NombreEquipo, 1, 5)

End

Public Sub ConvierteFechaLuckia(textofecha As String) As String

    Dim a As Integer
    Dim MesesNumeros As String[] = ["/01", "/02", "/03", "/04", "/05", "/06", "/07", "/08", "/09", "/10", "/11", "/12"]
    Dim MesesTexto As String[] = [" Ene", " Feb", " Mar", " Abr", " May", " Jun", " Jul", " Ago", " Sep", " Oct", " Nov", " Dic"]
    Dim broken As String

    a = -1
    For Each broken In MesesNumeros
        a += 1
        textofecha = Replace(textofecha, broken, MesesTexto[a])
    Next

    Return Upper$(textofecha)

End
